services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU15-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlServer@123
    ports:
      - "1435:1433"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SqlServer@123", "-C", "-Q", "SELECT 1"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 40s
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fitnessrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: redis:7-alpine
    container_name: fitnessredis
    ports:
      - "6379:6379"
  fitnessapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5080:8080"
      - "5081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      authenticationservice:
        condition: service_started
      profileservice:
        condition: service_started
      nutritionservice:
        condition: service_started
      fce:
        condition: service_started
      workoutservice:
        condition: service_started
      progresstrackingservice:
        condition: service_started
      notificationservice:
        condition: service_started
  fce:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__cs=Server=sqlserver,1433;Database=FceDB;User Id=sa;Password=SqlServer@123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - RabbitMq__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
    ports:
      - "7080:8080"
      - "7081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      nutritionservice:
        condition: service_started
  authenticationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__AuthenticationDatabase=Server=sqlserver,1433;Database=FitnessAuthentication;User Id=sa;Password=SqlServer@123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Redis__ConnectionString=redis:6379
      - RabbitMq__Host=rabbitmq
    ports:
      - "8082:8080"
      - "8083:8081"    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
  profileservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ProfileDatabase=Server=sqlserver,1433;Database=profileservice;User Id=sa;Password=SqlServer@123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Redis__ConnectionString=redis:6379
      - RabbitMq__Host=rabbitmq
    ports:
      - "3080:8080"
      - "3081:8081"    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
  nutritionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__NutritionDatabase=Server=sqlserver,1433;Database=FitnessNutrition;User Id=sa;Password=SqlServer@123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - RabbitMq__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
    ports:
      - "6080:8080"
      - "6081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
  progresstrackingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ProgressTrackingDatabase=Server=sqlserver,1433;Database=FitnessProgressTracking;User Id=sa;Password=SqlServer@123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Redis__ConnectionString=redis:6379
    ports:
      - "9080:8080"
      - "9081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
  workoutservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__cs=Server=sqlserver,1433;Database=FitnessWorkout;User Id=sa;Password=SqlServer@123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - RabbitMq__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
    ports:
      - "4080:8080"
      - "4081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - RabbitMq__Host=rabbitmq
    ports:
      - "10080:8080"
      - "10081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      rabbitmq:
        condition: service_started
