services:
  fitnessapp:
    image: ${DOCKER_REGISTRY-}fitnessapp
    build:
      context: .
      dockerfile: FitnessApp/Dockerfile
  fce:
    image: ${DOCKER_REGISTRY-}fce
    build:
      context: .
      dockerfile: Fce/Dockerfile
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile