// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionService.Data;

#nullable disable

namespace NutritionService.Data.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    partial class NutritionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutritionService.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Calories")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("CarbohydrateGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("FatGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("ProteinGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProteinGrams");

                    b.HasIndex("Type", "Calories");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealAllergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("MealId", "Name")
                        .IsUnique();

                    b.ToTable("MealAllergens", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealIngredients", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId", "StepNumber")
                        .IsUnique();

                    b.ToTable("MealInstructions", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TargetCalorieRangeMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("TargetCalorieRangeMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("TargetCalorieRangeMin", "TargetCalorieRangeMax");

                    b.ToTable("MealPlans", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("MealPlanId", "DayOfWeek", "MealTime", "SortOrder")
                        .IsUnique();

                    b.ToTable("MealPlanItems", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("MealId", "Name")
                        .IsUnique();

                    b.ToTable("MealTags", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealVariation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealVariations", (string)null);
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealAllergen", b =>
                {
                    b.HasOne("NutritionService.Domain.Entities.Meal", "Meal")
                        .WithMany("Allergens")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealIngredient", b =>
                {
                    b.HasOne("NutritionService.Domain.Entities.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealInstruction", b =>
                {
                    b.HasOne("NutritionService.Domain.Entities.Meal", "Meal")
                        .WithMany("Instructions")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealPlanItem", b =>
                {
                    b.HasOne("NutritionService.Domain.Entities.Meal", "Meal")
                        .WithMany("MealPlanItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutritionService.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("Items")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealTag", b =>
                {
                    b.HasOne("NutritionService.Domain.Entities.Meal", "Meal")
                        .WithMany("Tags")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealVariation", b =>
                {
                    b.HasOne("NutritionService.Domain.Entities.Meal", "Meal")
                        .WithMany("Variations")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Allergens");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("MealPlanItems");

                    b.Navigation("Tags");

                    b.Navigation("Variations");
                });

            modelBuilder.Entity("NutritionService.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
